# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.srcs/sources_1/bd/adc_tech/ip/adc_tech_auto_pc_5/adc_tech_auto_pc_5.xci
# IP: The module: 'adc_tech_auto_pc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.gen/sources_1/bd/adc_tech/ip/adc_tech_auto_pc_5/adc_tech_auto_pc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_tech_auto_pc_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.srcs/sources_1/bd/adc_tech/ip/adc_tech_auto_pc_5/adc_tech_auto_pc_5.xci
# IP: The module: 'adc_tech_auto_pc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.gen/sources_1/bd/adc_tech/ip/adc_tech_auto_pc_5/adc_tech_auto_pc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_tech_auto_pc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
