# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/work/MVT_ADC_TECH/constraints/io_pins.xdc

# Block Designs: bd/adc_tech/adc_tech.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech || ORIG_REF_NAME==adc_tech} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_xbar_0/adc_tech_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_xbar_0 || ORIG_REF_NAME==adc_tech_xbar_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_axi_interconnect_0_0/adc_tech_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_axi_interconnect_0_0 || ORIG_REF_NAME==adc_tech_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_clk_wiz_0_0/adc_tech_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_clk_wiz_0_0 || ORIG_REF_NAME==adc_tech_clk_wiz_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_jtag_axi_0_0/adc_tech_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_jtag_axi_0_0 || ORIG_REF_NAME==adc_tech_jtag_axi_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_proc_sys_reset_0_0/adc_tech_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_proc_sys_reset_0_0 || ORIG_REF_NAME==adc_tech_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_zynq_ultra_ps_e_0_0/adc_tech_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==adc_tech_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_util_ds_buf_0_2/adc_tech_util_ds_buf_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_util_ds_buf_0_2 || ORIG_REF_NAME==adc_tech_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_axi_gpio_0_0/adc_tech_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_axi_gpio_0_0 || ORIG_REF_NAME==adc_tech_axi_gpio_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_data_splitter_0_0/adc_tech_data_splitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_data_splitter_0_0 || ORIG_REF_NAME==adc_tech_data_splitter_0_0} -quiet] -quiet

# IP: bd/adc_tech/ip/adc_tech_auto_pc_0/adc_tech_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_tech_auto_pc_0 || ORIG_REF_NAME==adc_tech_auto_pc_0} -quiet] -quiet

# XDC: c:/work/MVT_ADC_TECH/adc_tech/adc_tech.gen/sources_1/bd/adc_tech/adc_tech_ooc.xdc
