# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/Technology/Vivado/adc_mvt/adc_mvt.srcs/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1.xci
# IP: The module: 'mvt_top_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Technology/Vivado/adc_mvt/adc_mvt.gen/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvt_top_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/work/Technology/Vivado/adc_mvt/adc_mvt.gen/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvt_top_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/work/Technology/Vivado/adc_mvt/adc_mvt.srcs/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1.xci
# IP: The module: 'mvt_top_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/Technology/Vivado/adc_mvt/adc_mvt.gen/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvt_top_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/work/Technology/Vivado/adc_mvt/adc_mvt.gen/sources_1/bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mvt_top_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
