# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/mvt_top/mvt_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top || ORIG_REF_NAME==mvt_top} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_zynq_ultra_ps_e_0_0/mvt_top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mvt_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_clk_wiz_0_0/mvt_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_clk_wiz_0_0 || ORIG_REF_NAME==mvt_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_proc_sys_reset_0_0/mvt_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mvt_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_util_ds_buf_0_0/mvt_top_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_util_ds_buf_0_0 || ORIG_REF_NAME==mvt_top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_util_ds_buf_0_1/mvt_top_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_util_ds_buf_0_1 || ORIG_REF_NAME==mvt_top_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_util_ds_buf_0_2/mvt_top_util_ds_buf_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_util_ds_buf_0_2 || ORIG_REF_NAME==mvt_top_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_c_counter_binary_0_1/mvt_top_c_counter_binary_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_c_counter_binary_0_1 || ORIG_REF_NAME==mvt_top_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlslice_0_1/mvt_top_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlslice_0_1 || ORIG_REF_NAME==mvt_top_xlslice_0_1} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlconcat_0_0/mvt_top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlconcat_0_0 || ORIG_REF_NAME==mvt_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlconstant_0_0/mvt_top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlconstant_0_0 || ORIG_REF_NAME==mvt_top_xlconstant_0_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlslice_0_2/mvt_top_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlslice_0_2 || ORIG_REF_NAME==mvt_top_xlslice_0_2} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlslice_1_0/mvt_top_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlslice_1_0 || ORIG_REF_NAME==mvt_top_xlslice_1_0} -quiet] -quiet

# IP: bd/mvt_top/ip/mvt_top_xlslice_1_1/mvt_top_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mvt_top_xlslice_1_1 || ORIG_REF_NAME==mvt_top_xlslice_1_1} -quiet] -quiet

# XDC: c:/work/Technology/Vivado/adc_mvt/adc_mvt.gen/sources_1/bd/mvt_top/mvt_top_ooc.xdc
