webtalk_init -webtalk_dir C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/adc_to_bram_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 22 09:22:05 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "788184fe-d1b3-4df4-bc78-6dcba078ee8f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a579572a191344d6b971e0746032eb8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 7 265" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2381 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1823873235 -regid "" -xml C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/adc_to_bram_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/adc_to_bram_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/adc_to_bram_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
