set_property PACKAGE_PIN H9 [get_ports clk_in_p]
set_property IOSTANDARD LVDS [get_ports clk_in_p]
set_property IOSTANDARD LVDS [get_ports clk_in_n]
set_property PACKAGE_PIN F17 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_scl]
set_property PACKAGE_PIN F16 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_sda]


set_property PACKAGE_PIN AL11 [get_ports {gpio_led[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {gpio_led[7]}]
set_property PACKAGE_PIN AL13 [get_ports {gpio_led[1]}]
set_property PACKAGE_PIN AK13 [get_ports {gpio_led[2]}]
set_property PACKAGE_PIN AE15 [get_ports {gpio_led[3]}]
set_property PACKAGE_PIN AM8 [get_ports {gpio_led[4]}]
set_property PACKAGE_PIN AM9 [get_ports {gpio_led[5]}]
set_property PACKAGE_PIN AM10 [get_ports {gpio_led[6]}]
set_property PACKAGE_PIN AM11 [get_ports {gpio_led[7]}]

set_property PACKAGE_PIN L15 [get_ports {fmc_led0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_led0[0]}]

set_property PACKAGE_PIN C9 [get_ports {fmc_led1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_led1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_led2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_led3[0]}]
set_property PACKAGE_PIN E8 [get_ports {fmc_led2[0]}]
set_property PACKAGE_PIN F8 [get_ports {fmc_led3[0]}]
set_property DRIVE 12 [get_ports {fmc_led0[0]}]
set_property DRIVE 12 [get_ports {fmc_led1[0]}]
set_property DRIVE 12 [get_ports {fmc_led2[0]}]
set_property DRIVE 12 [get_ports {fmc_led3[0]}]
