webtalk_init -webtalk_dir C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 10 15:36:47 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212317235_0_0_245" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c848898f-f1dd-4e33-9f9e-0475c5e1cff8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a579572a191344d6b971e0746032eb8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.38_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14756_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3787301632 -regid "212317235_0_0_245" -xml C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/work/Technology/Vivado/MVT_ADC_TECH/adc_tech/adc_tech.sim/sim_1/behav/xsim/xsim.dir/i2c_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
